repos:
  - repo: local
    hooks:
      - id: lint
        name: go lint
        entry: just lint
        language: system
        pass_filenames: false
      - id: testrace
        name: go tests (race)
        entry: just testrace
        language: system
        pass_filenames: false
