name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - uses: extractions/setup-just@v3
      - name: Install dependencies(just and golangci-lint)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b /usr/local/bin v2.2.1
      - name: Lint code
        run: just lint
      - name: Test & collect coverage
        run: just cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out